export const REGISTER_USER='REGISTER_USER';
export const REGISTER_USER_ERROR='REGISTER_USER_ERROR';

export const LOGIN_USER='LOGIN_USER';
export const LOGIN_USER_ERROR='LOGIN_USER_ERROR';

export const STUDENT_LIST='STUDENT_LIST';
export const STUDENT_LIST_ERROR='STUDENT_LIST_ERROR';

export const FACULTY_LIST='FACULTY_LIST';
export const FACULTY_LIST_ERROR='FACULTY_LIST_ERROR';

export const EVENT_LIST='EVENT_LIST';
export const ADD_EVENT='ADD_EVENT';
export const DELETE_EVENT='DELETE_EVENT';
export const EDIT_EVENT='EDIT_EVENT';


export const ADD_FACULTY='ADD_FACULTY';

export const COUNT_FACULTY='COUNT_FACULTY';
export const COUNT_STUDENT='COUNT_STUDENT';
export const COUNT_EVENTS='COUNT_EVENTS';
